#!/bin/sh
cd ../..
rm -rf ./build
mkdir build
cd ./build
cmake ..
make -j4
cd ..
./build/src/autotester/autotester ../Tests37/iter1/simple_source_code.txt ../Tests37/iter1/simple_affects_query.txt ../Tests37/out.xml