#!/bin/sh
cd ../..
rm -rf ./build
mkdir build
cd ./build
cmake ..
make -j4
cd ..
./build/src/autotester/autotester ../Tests37/basicmultiproceduretest/sourcecode.txt ../Tests37/basicmultiproceduretest/modifiesPtests.txt ../Tests37/out.xml