#!/bin/sh
cd ../..
rm -rf ./build
mkdir build
cd ./build
cmake ..
make -j4
cd ..
./build/src/autotester/autotester ../Tests37/nested_while_test/iter1_nested_while_source.txt ../Tests37/nested_while_test/iter1_nested_while_uses_queries.txt ../Tests37/out.xml